### ISSUE TITLE
rust complier

### ISSUE THREAD

**Issue by wangjiawen2013** [pwwang/plotnine-prism#1]
Hi,
wow, prism is very beautiful!
I met an error when installing plotnine-prism, the error is about rust compiling. Does plotnine-prism need rust or rustc complier ?

**Comment by pwwang** [comment]
That's probably because of the `rtoml` dependency. There are alternatives but could you post the python version that you are using? and maybe the OS?

**Comment by wangjiawen2013** [comment]
This problem is solved. It's a bug or our server, not plotnine-prism.
